-  name:
   debug:
     msg:  "[WORKER] K8S_TOKEN_HOLDER - O TOKEN: {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

-  name:
   debug:
     msg:  "[WORKER] K8S_TOKEN_HOLDER - O HASH: {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

-  name: Remvendo o cluster
   command:
     kubeadm reset --force
   register: kubeadm_reset


-  name: Adicionando o worker ao cluster
   shell:
     kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }}
     --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}
     {{ K8S_MASTER_NODE_IP }}:{{ k8S_API_SECURE_PORT }}
